name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      # Make Gradle wrapper executable
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      # Start Android Emulator
      - name: Start Android Emulator
        run: |
          nohup $ANDROID_HOME/emulator/emulator -avd my_avd -no-window -no-boot-anim &
          adb wait-for-device
          adb shell input keyevent 82  # Unlock the emulator screen

      # Run Gradle build with stacktrace
      - name: Build with Gradle
        run: ./gradlew build --stacktrace --info

      # Run UI tests with stacktrace
      - name: Run UI tests
        run: ./gradlew connectedAndroidTest --stacktrace

      # Stop Android Emulator
      - name: Stop Android Emulator
        run: adb -e emu kill
